version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
  laravel:
    build:
      context: ./laravelapp
    ports:
      - "9000:9000"
    volumes:
      - ./laravelapp/laravel:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql

  laravel-nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./laravelapp/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel
  vue:
    build:
      context: ./vueapp
    ports:
      - "8000:80"
    volumes:
    #   - ./vueapp/dist:/usr/share/nginx/html
      - ./vueapp/nginx.conf:/etc/nginx/nginx.conf


  vue-nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./vueapp/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vue